### ISSUE TITLE
css & text overflow & ellipsis & multiline

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/learning#35]
# css & text overflow & ellipsis & multiline

> css text overflow ellipsis multiline

https://github.com/xyzdata/RAIO/issues/213

```css
.fv-important-infos-table-tbody>tr:nth-of-type(1)>td:last-child,
.fv-important-infos-table-tbody>tr:nth-of-type(2)>td:last-child {
    /* background: #f0f; */
    /* text-wrap: all; */
    overflow: hidden;
    word-wrap: break-word;
    text-overflow: ellipsis;
    /* white-space: nowrap; */
    /* width: 400px; */
    /* height: calc(32px + 32px); */
    /* line-height: 32px; */
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    /* font-size: 13px; */
}

```

https://codepen.io/martinwolf/pen/qlFdp
